name: Equinox
version: ${project.version}
main: net.equinox.wild.equinox.Equinox
api-version: 1.18
authors: [ WildGames500 ]
depend: [ Vault, HolographicDisplays ]
commands:
  cpu:
    description: Returns pong!
    usage: /<command> [test]
  eq:
    description: Returns pong!
    usage: /<command> [ping|tphere|tp|kill|name|info]
  eqa:
    description: Returns pong!
    usage: /<command> [heat]
  rankup:
    description: Returns pong!
    usage: /<command> [player]
  countdown:
    description: Returns Countdown!
    usage: /<command>
  access:
    description: Returns pong!
    usage: /<command>
  heart:
    description: Returns pong!
    usage: /<command> [color code]
  diamond:
    description: Returns pong!
    usage: /<command> [color code]
  star:
    description: Returns pong!
    usage: /<command> [color code]
  flower:
    description: Returns pong!
    usage: /<command> [color code]
  bell:
    description: Returns pong!
    usage: /<command>
  testill:
    description: Shh this doesn't exist
    usage: /testill Who knows?
