name: Equinox
version: ${project.version}
main: net.equinox.wild.equinox.Equinox
api-version: 1.16
authors: [ WildGames500 ]
depend: [Vault]
commands:
  eq:
    description: Returns pong!
    usage: /<command> [ping|tphere|tp|kill|name]
